### PR TITLE
Add a 'outputTableName' argument to support custom sample names

### PR DESCRIPTION
**Pull request by jeffdesc**
#### Description of the changes

All results of all service checks are being added to the "NagiosServiceCheckSample", but in most situations you want to split this up to have custom samples per service check. This way you can structure your data in New Relic Insights properly.

This code is in use in a forked version in our monitoring system and has been tested, it's been working as expected.

However on every major code change, I've to re-create a patch which creates too much hassle. This way it can be pushed into the NRI Nagios code base.

### Author

- [ ] the PR should focus on a single subject. Change only relevant files to the problem you’re working on
Clean and format the code
- [ ] add unit tests for your changes and make sure all unit tests are passing
- [ ] add a risk label after carefully considering the "blast radius" of your changes
- [ ] describe the _intent_ of your changes in the description. don't just rewrite your code in prose
- [ ] assign at least one reviewer
- [ ] address the feedback 

### Reviewer

- [ ] review code for readability
- [ ] verify that high risk behavior changes are well tested
- [ ] check license for any new external dependency
- [ ] ask questions about anything that isn't clear and obvious
- [ ] approve the PR when you consider it's good to merge

### CODE REVIEW

**Comment by camdencheek** [comment]
Hi @jeffdesc -- Thanks for the PR. I'll take a look over this sometime today

**Comment by camdencheek** [comment]
Looks great. I'll get this released in the next couple of days

**Comment by jeffdesc** [comment]
Hey @camdencheek, thanks for the feedback. Any idea when this will be released? We're stuck at the moment and awaiting this release to proceed.

**Comment by camdencheek** [comment]
@jeffdesc Whoops -- thought I had included it in the last release. I'll go ahead and make a release right now. Sorry about that!

**Comment by jeffdesc** [comment]
No problem @camdencheek, thank you very much!

**Pull request merged**
